### ISSUE TITLE
tab length settings ignored

### ISSUE THREAD

**Issue by DRempfer** [ashthespy/Atom-LaTeX#134]
Subject says it all: No matter what tab length I set in Editor Settings (these are supposedly also used as default in the LaTeX package, as shown in the package settings pages), Atomic Soft Tabs as well as the spacing of the Indent Guides remain stuck at Atom's default setting of two spaces.
**Update:** I tried changing the tab length setting in the package settings, and if I set the tab length to something other than the Atom default, things work. However, if I set it to Atom's default value, the input field switches to show "Default: n", with n the default set for Atom, but then the Indent Guide and Atomic Soft Tabs will switch back to a value of 2.

**Comment by rddunphy** [comment]
I'm having this problem, too - it doesn't seem to be possible to have a tab length of 4 spaces. Is there a way to use the build functionality of atom-latex but disable the grammars? https://github.com/area/language-latex does a good job of syntax highlighting already.

**Comment by ashthespy** [comment]
Found the issue in #225
