### ISSUE TITLE
Wrap existing code inside \begin{environment} \end{environment}

### ISSUE THREAD

**Issue by Doekeb** [ashthespy/Atom-LaTeX#141]
I frequently come across the following use case:

I'll type an equation that fits nicely on a single line like so:

`$$ y = x^2 - 2x + 1 $$`

Then later come back and decide I'd actually like this equation to be labeled, so I need to change it to:

```
\begin{equation} \label{my_eq}
     y = x^2 - 2x + 1
\end{equation}
```

Or perhaps instead I'd like to continue with the equality using an align or align* environment:

```
\begin{align*}
     y &= x^2 - 2x + 1 \\
     &= (x-1)(x-1) \\
     &= (x-1)^2
\end{align*}
```

It would be great to have a tool and a keyboard shortcut (maybe ctrl-E for environment) that operates similar to `$`, `[`, `{`, or `(` combined with the autocomplete for `\begin`. That is, highlight the code that you would like to be wrapped (in my example, `y = x^2 - 2x + 1`), execute the keyboard shortcut, and the result will be the highlighted code, wrapped as follows:

```
\begin{[cursor goes here]}
     [highlighted code goes here]
\end{[cursor goes here]}
```

with two cursors inside the two pairs of braces so you only need to type the environment name once. A `tab` keystroke should move the cursor to the end of the wrapped text like so:

```
\begin{}
     [highlighted code goes here][cursor is now here]
\end{}
```

I wouldn't be surprised if this feature already exists and I'm just too dense to find it. If so, please point me in the right direction!

**Comment by ashthespy** [comment]
@Doekeb  This feature doesn't exist, but may be something to consider, given James's VS Code counterpart https://github.com/James-Yu/LaTeX-Workshop/issues/246 provides this feature
