### ISSUE TITLE
Fail to compile file with dot in the name

### ISSUE THREAD

**Issue by juliabeliaeva** [ashthespy/Atom-LaTeX#205]
Package fails to compile files with dot in the name. For example, for a file called `test.file.tex` I get the following error:

```
> pdflatex -synctex=1 -interaction=nonstopmode -file-line-error test

This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `test'.
<*> test
        
(Press Enter to retry, or Control-D to exit)
Please type another input file name
! Emergency stop.
<*> test
        
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.
```
Seems that the extension is trimmed incorrectly from the file name.

atom-latex version [0.8.6] 2019-07-01

**Comment by ashthespy** [comment]
Hmm this is an artefact of https://github.com/James-Yu/Atom-LaTeX/pull/97 - where everything after the first period are stripped out of the filename to support for non default file extensions (`.tikz`,`.Rnw`). 
This was done to handle cases such as `file.tex.tikz` (https://github.com/James-Yu/Atom-LaTeX/pull/89#issuecomment-321505504) 

I am unsure how to strip filenames to incorporate your use case as well here.
