### ISSUE TITLE
Allow setting root file using settings

### ISSUE THREAD

**Issue by EnochMakenp** [ashthespy/Atom-LaTeX#212]
There are a few package around that allow to create project in Atom (I'm using project-manager like 1 million other users :-), and for them it will be interesting to have a way to set the root directory, something like:
atom-latex.root : "\\path\\to\\my\\rootFile.tex

That will remove the need to have the !TEX pragma in the file headers, and make it much more simple :-)
I'm trying to hork something locally, but I'm too new to CoffeeScript to really fathom what to do, maybe an observer is needed ?

Thanks for your work !

**Comment by ashthespy** [comment]
Have you seen the Readme's [Set per-project LaTeX toolchain](https://github.com/ashthespy/Atom-LaTeX#-set-per-project-latex-toolchain) section? Does that do what you need?

I have in my `init.coffee` the following snippet

```coffee
atom.commands.add 'atom-workspace',
  'atom-latex:init': () =>
    Fname = atom.workspace.getActiveTextEditor().getTitle() || 'main.tex'
    Fdir = atom.workspace.project.relativizePath(atom.workspace.getActiveTextEditor().getPath())[0] || atom.workspace.project.getPaths()[0]
    config =
      root: Fname
      toolchain: 'arara %DOC -v'
      latex_ext: [".tikz",".tex"]
    fs = require 'fs'
    fs.writeFile("#{Fdir}/.latexcfg",JSON.stringify(config, null, 4),\ # Indendted JSON
      'utf8', (e) ->
        console.log e if e?
        console.log " .latexcfg created for #{Fname} in #{Fdir}"
        )
```

**Comment by ashthespy** [comment]
I had some time to check out [`atom-project-manager`](https://github.com/danielbrodin/atom-project-manager) and since it just reads the global `config.cson` you could simple just customise `atom-latex.custom_toolchain` directly. So something along the lines of
```
"atom-latex.custom_toolchain" : "%TEX %ARG \path\to\my\rootFile.tex 
&& %BIB \path\to\my\rootFile && %TEX %ARG %DOC.%EXT && %TEX %ARG \path\to\my\rootFile.tex"
```

PS: you might have to play around with escaping quotes and the slashes if its expecting JSON..

**Comment by EnochMakenp** [comment]
Thanks for your help - customizing the toolchain may in fact be a good enough workaround solution !
