### ISSUE TITLE
[Feature Request] Add switch to select latex grammar

### ISSUE THREAD

**Issue by BambOoxX** [ashthespy/Atom-LaTeX#215]
I personally like to use the `language-latex2e` package as my latex grammar. 
However, there is a conflict with the default package settings switching back to your grammar. 
Would it be possible to add a swith to activate or select a specific grammar ?
Thanks, and keep up the good work.

**Comment by ashthespy** [comment]
Will have a look, but no promises - trying to keep the package as simple and minimal as possible.
