### ISSUE TITLE
Uncaught TypeError: this.latex.logger.debuglog.error is not a function

### ISSUE THREAD

**Issue by shanwai1234** [ashthespy/Atom-LaTeX#216]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.1
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.8.10

### Stack Trace

Uncaught TypeError: this.latex.logger.debuglog.error is not a function

```
At /Users/zhikai/.atom/packages/atom-latex/lib/viewer.coffee:83

TypeError: this.latex.logger.debuglog.error is not a function
    at Viewer.module.exports.Viewer.openViewerNewWindow (/packages/atom-latex/lib/viewer.coffee:83:30)
    at Viewer.module.exports.Viewer.openViewer (/packages/atom-latex/lib/viewer.coffee:71:8)
    at HTMLElement.click (/packages/atom-latex/lib/view/panel.js:112:86)
```

### Commands

```
     -2:52.1.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close.has-buttons)
```

### Non-Core Packages

```
atom-latex 0.8.10 
latex 0.50.2 
pdf-view 0.71.0 
```

**Comment by ashthespy** [comment]
Particular error fixed with 7fc98420c82b8346e9dc884860b113d39ca141a9.

This is triggered because there is no PDF file for the viewer to open.
