### ISSUE TITLE
Uncaught RangeError: Unsupported time zone specified undefined

### ISSUE THREAD

**Issue by brent-lauder** [ashthespy/Atom-LaTeX#218]
Steps to reproduce:

1. searched atom-LaTeX in install menu
2. clicked install. 

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: linux 5.2.7-100.fc29.x86_64
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.8.10

### Stack Trace

Uncaught RangeError: Unsupported time zone specified undefined

```
At /home/brent/.var/app/io.atom.Atom/data/packages/atom-latex/lib/logger.coffee:114

RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at Date.toLocaleTimeString (native)
    at /packages/atom-latex/lib/logger.coffee:114:65)
    at /packages/atom-latex/lib/logger.coffee:8:17)
    at /packages/atom-latex/lib/main.coffee:115:15)
    at Object.lazyLoad (/packages/atom-latex/lib/main.coffee:23:14)
    at /packages/atom-latex/lib/main.coffee:16:30
```

### Commands

```
     -9:59.3.0 editor:newline (input.hidden-input)
  2x -9:57 core:backspace (input.hidden-input)
     -9:52.5.0 core:move-up (input.hidden-input)
     -9:51.7.0 core:move-down (input.hidden-input)
     -9:36.3.0 core:backspace (input.hidden-input)
     -9:35.2.0 editor:newline (input.hidden-input)
  3x -9:22.3.0 core:backspace (input.hidden-input)
     -9:19.5.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.10 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-monokai-black-ui 0.3.0 
autocomplete-bibtex 1.2.7 
busy-signal 2.0.1 
grammar-token-limit 0.1.1 
intentions 1.1.5 
language-latex 1.2.0 
language-tex 0.4.0 
linter 2.3.1 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-spell-project 0.2.0 
linter-ui-default 1.8.0 
minimap 4.29.9 
minimap-linter 2.2.1 
monokai 0.24.0 
pigments 0.40.2 
todo-show 2.3.2 
```

**Comment by ashthespy** [comment]
Looks like the chrome version currently in Atom can't figure out what time zone is configured currently. Do you know if your OS settings has a time zone configured?

**Comment by brent-lauder** [comment]
Yes, it was manually configured when I implemented the OS.  I run fedora 29 on the pc that had the issue. I should mention that I'm a bit of a newbie. 

I retried installing once more before submitting the issue. First time I tried install I had the automatic time zone in the OS GUI settings turned off, (but the time zone was definitely set, manually). I uninstalled and changed the auto time zone setting on, which had no effect and the same issue occurred. I restarted atom between each try. 

Let me know if there is anything you want me to try or can get back to you with. 
I'm also a bash noob, as so any command line instructions you want to give to help debug the issue I'll probably not be proficient in implementing unless the directions are child-proof. 

Thanks for the quick reply.

**Comment by ashthespy** [comment]
Unfortunately it seems to be more an OS/Chrome issue ([bugs.chromium.org](https://bugs.chromium.org/p/chromium/issues/detail?id=811403)) than this package, so I can't help much.
Try launching the dev console in Atom (Ctrl+Shift+I) and entering the following to check if its picking up the right timezone.
```
new Intl.DateTimeFormat('en-US', { timeZoneName: 'long'}).resolvedOptions()
```
