### ISSUE TITLE
Unable to build PDF

### ISSUE THREAD

**Issue by JPUnD** [ashthespy/Atom-LaTeX#222]
So before i install `atom-latex` i've installed the `latex` package, which didn't work as expected (nothing was happening, wasn't founding the commands in the command palette also), and now in this package, all the commands show up, but it doesn't do anything anyways.

I'm pretty certain i'm doing something wrong, just not sure where.

I've installed the `texlive-most` using pacman (details down below), and installed `atom-latex` from atom itself. Upon running build here, all i get (when i press ctrl+shift+i) is the following error:
```
/home/undercover/.atom/packages/atom-latex/lib/builder.coffee:37 Uncaught (in promise) TypeError: Cannot read property 'view' of undefined
    at /home/undercover/.atom/packages/atom-latex/lib/builder.coffee:23
(anonymous) @ /home/undercover/.atom/packages/atom-latex/lib/builder.coffee:37
```

### System:
Manjaro stable (kernel 4.16.69)
Atom (1.39.1)

**Comment by ashthespy** [comment]
@JPUnD  Seems to be some issue with the view panel, and not really your TeX configuration. 
Could you upgrade to a more recent version of Atom (v1.40.1 is current) and check if the issue persists?

**Comment by JPUnD** [comment]
Honestly, this is the most updated version on the official repos, although it is flagged "out of date", but i imagine it must be for a reason.

One thing tho, how would the view panel have any effect on rendering latex? I'm not trying to open it, i'm just trying to render it, i wouldn't mind opening it myself.

**Comment by ashthespy** [comment]
This isn't an issue with the PDF viewer, but the notification panel that shows the build status seems to be throwing up issues. You could try installing an older version of the package `apm install atom-latex@0.8.8` - that version uses  an older version of `etch` that is used to render these notification panels.

**Comment by JPUnD** [comment]
Got the same error anyways

**Comment by ashthespy** [comment]
What package do you use to install Atom? There are two versions, and the official version uses a different version of Electron that could lead to issues. (https://github.com/ashthespy/Atom-LaTeX/issues/204#issuecomment-508809012). Try with [`atom-editor-bin`](https://aur.archlinux.org/packages/atom-editor-bin/) that contains the correct bundled version of Electron.

**Comment by JPUnD** [comment]
Wouldn't it conflict with pre-installed electron and cause issues in other electron-based software?

Atom 1.40.1 is now on arch official repository, i think it will be a matter of time until manjaro gets it too, so i guess i'll wait to see if the problem is fixed in the newer versions, and try to see if i can get more information to make this issue clearer.

**Comment by ashthespy** [comment]
No, Atom comes with its own bundled version of Electron, to avoid such issues. 
You can look at the other issue for some ideas on how to determine if you have the right version of electron for your version of Atom.

**Comment by ashthespy** [comment]
Closing this for now, will reopen if are still facing issue with the package with the bundled electron.
