### ISSUE TITLE
pdf preview window always resizes when compiling

### ISSUE THREAD

**Issue by vthuongt** [ashthespy/Atom-LaTeX#223]
Hello,
I am using atom-latex on Windows10 and Ubuntu. When I compile my document on Ubuntu the preview window refreshes and shows the changes made. The preview window stays at the same position and size. However The same procedure on Windows leads to the PDF-Viewer window to reset to the last state when it wasn't docked. With docked I mean that the window was snapped to the left/right side of the screen. (by dragging to edge of the screen or pushing Win+left/tight arrow):
Example:
* Position 1 (floating): (x,y), size = 200px x 200px
* Compile -> Position doesn't change, only window refreshes
* Dock window to left/right side of screen
* Compile -> Position changes back to floating position 1 

I tried deactivating the setting "Focus PDF viewer window after building" but the window would still jump around. I also tried changing the setting "Preview PDF after building process" to "Do nothing" but this didn't change the jmping behaviour. How can I fix this problem?

**Comment by ashthespy** [comment]
I notice this as well, on Win10. I shall investigate when I get some time!
