### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by noumanschaudhry** [ashthespy/Atom-LaTeX#224]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.8.10

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\noman\.atom\packages\atom-latex\lib\builder.coffee:190

TypeError: Cannot read property '0' of undefined
    at Builder.module.exports.Builder.custom_toolchain (/packages/atom-latex/lib/builder.coffee:190:40)
    at Builder.module.exports.Builder.setCmds (/packages/atom-latex/lib/builder.coffee:158:10)
    at Builder.module.exports.Builder.build (/packages/atom-latex/lib/builder.coffee:16:6)
    at /packages/atom-latex/lib/main.coffee:34:53)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:744892)
    at EventEmitter.t (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:752815)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -0:21.1.0 atom-latex:build-here (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.10 
Hydrogen 2.12.0 
pigments 0.40.2 
```

**Comment by ashthespy** [comment]
Hi, how do you set your [LaTeX root file](https://github.com/ashthespy/Atom-LaTeX#setting-the-latex-root-file)? It would seem that it's unable to determine what the filename is and hence throwing an error.

**Comment by noumanschaudhry** [comment]
Hey Ash, yes i did, though i am not completely sure if i did it in the right way. I dont really understand whats the point of root file and what it should contain :/. I just downloaded this (https://gitlab.com/baumhaus33/Patent-Linzenz-Impressum/blob/master/.latexcfg) .latexcfg file and put it as root

**Comment by ashthespy** [comment]
@noumanschaudhry that `.latexcfg` file sets `{ "root" : "./latex/Main.tex" }`. 
With the same project, and editor window open, can you open up the dev console (`ctrl` + `shift` + `i`)  and check the outputs of the following? (It should similar to this..)

```js
> atom_latex.latex.manager.findMain()
< true
> atom_latex.latex.mainFile
< "~\Main.tex"
> atom_latex.latex.manager.getDocandExt(atom_latex.latex.mainFile)
< (2) ["main", "tex"]

**Comment by noumanschaudhry** [comment]
@ashthespy this is what i get:

![image](https://user-images.githubusercontent.com/9056672/65973541-68a43d00-e463-11e9-9b15-136edcdff022.png)

**Comment by ashthespy** [comment]
Um, what is `latexcfg.tex`?

**Comment by paulequilibrio** [comment]
I'm getting the same error:

```js
Uncaught TypeError: Cannot read property '0' of undefined
    at Builder.module.exports.Builder.custom_toolchain (builder.coffee? [sm]:144)
    at Builder.module.exports.Builder.setCmds (builder.coffee? [sm]:113)
    at Builder.module.exports.Builder.build (builder.coffee? [sm]:7)
    at HTMLElement.click (panel.js? [sm]:70)
module.exports.Builder.custom_toolchain @ builder.coffee? [sm]:190
module.exports.Builder.setCmds @ builder.coffee? [sm]:155
module.exports.Builder.build @ builder.coffee? [sm]:16
click @ panel.js? [sm]:111
```

And when I run the commands below

> ```js
> > atom_latex.latex.manager.findMain()
> < true
> > atom_latex.latex.mainFile
> < "~\Main.tex"
> > atom_latex.latex.manager.getDocandExt(atom_latex.latex.mainFile)
> < (2) ["main", "tex"]
> ```

the third one output is `undefined`. The first and the second commands output's OK.

**Comment by ashthespy** [comment]
> My main file has `.xtx` extension. The package only works with `.tex` files?

Did you add the custom configuration as described in the Readme section on [Support for non `.tex` files](https://github.com/ashthespy/Atom-LaTeX#support-for-non-tex-files)?

**Comment by paulequilibrio** [comment]
> Did you add the custom configuration as described in the Readme section on [Support for non `.tex` files](https://github.com/ashthespy/Atom-LaTeX#support-for-non-tex-files)?

Oh, I totally forget about that. Thanks for pointed it out.

I'm getting trouble now with the toolchain. I'm using `latexmk` with a `.latexmkrc` file. The package can read this `.latexmkrc` file?
