### ISSUE TITLE
Tab size setting bug

### ISSUE THREAD

**Issue by newton108** [ashthespy/Atom-LaTeX#225]
I'm not sure whether this was intended to be a feature or bug.

1. When setting type size in the setting of Atom-LaTex, starting with default value for each grammars, if LaTeX Grammar was set first, then it affects every other grammars, e.g. setting tab size of LaTeX Grammar to 6 resulting tab size 6 for every grammars. Then if the tab size of  LaTeX Grammar was changed again, e.g. to 5, it affects LaTeX Grammar only. This is very confusing.

2. It conflicts the editor tab size setting in the following way. After editor tab size was set,
```
Editor:
    tabLength: 4
```
It is not possible to set the tab size for LaTeX Grammar to the same value via UI, i.e. not possible to set
```
".latex.tex.text":
  editor:
    tabLength: 4
```
without editing the config file.
The consequence is if the tab size for LaTeX Grammar was not set initially and the editor tab size was set to 4, it is not possible to set it also to 4 via UI, and it fall back to default tab size of the plugin, which is 2.

**Comment by ashthespy** [comment]
I am not sure I fully understand the issue. The tab settings are language specific and scoped to each language's grammar, and *shouldn't* effect the global editor settings.
Or do you mean setting TabLenght for say LaTeX grammar effects Beamer/Tex/Memoir etc as well?

**Comment by newton108** [comment]
> Or do you mean setting TabLength for say LaTeX grammar effects Beamer/Tex/Memoir etc as well?
Yes.

**Comment by ashthespy** [comment]
This is due to how the language scopes are setup - Beamer,Memoir  and TikZ are all under the root scope of `text.tex.latex` and hence have the same `tabLength` settings. 

| Grammar    | Scope |
| ------------- | ---|
| LaTeX   | `text.tex.latex`  |
|LaTeX Beamer |`text.tex.latex.beamer`|
|LaTeX Memoir |`text.tex.latex.memoir`|
|TikZ | `text.tex.latex.tikz`| 
| TeX |  `text.tex`   |
|LaTeX Log | `text.log.latex`|

I would reckon if you really want them to be different, you could set them explicitly in your config file

**Comment by newton108** [comment]
Sure, but if tab length Beamer/Tex/Memoir etc was not set in config file and setting tab size for LaTeX via UI, it explicitly sets all of them in my config file, is this intended?
Because this cause the problem that if I set a new tab length for LaTeX via UI, it does not affect tab length for Beamer/Tex/Memoir, since it was considered these tab length was customised.

**Comment by ashthespy** [comment]
I get what you mean now. 
Honestly, IIR, these settings are handled by Atom's internals, and not explicitly by the package. Possibly a better idea to post it upstream at [atom/atom](https://github.com/atom/atom) to get more inputs.

**Comment by newton108** [comment]
And what about this issue?

> 2. It conflicts the editor tab size setting in the following way. After editor tab size was set,
> 
> ```
> Editor:
>     tabLength: 4
> ```
> 
> It is not possible to set the tab size for LaTeX Grammar to the same value via UI, i.e. not possible to set
> 
> ```
> ".latex.tex.text":
>   editor:
>     tabLength: 4
> ```
> 
> without editing the config file.
> The consequence is if the tab size for LaTeX Grammar was not set initially and the editor tab size was set to 4, it is not possible to set it also to 4 via UI, and it fall back to default tab size of the plugin, which is 2.

Basically this says if tab length for ".latex.tex.text" is not set, it disrespect the customised editor tab length, which is fine, but it is not possible to set via UI.

**Comment by ashthespy** [comment]
>Basically this says if tab length for ".latex.tex.text" is not set, then it disrespects the customised editor tab length, which is fine, but it is not possible to set via UI.

From a quick skim of [Atoms's docs](https://blog.atom.io/2014/10/31/language-scoped-config.html), this should work by setting up your your global value:  
```cson
'global': # all languages unless overridden
  'editor':
    'tabLength': 4
```
I just tried this on Atom 1.40.1 on Win10, and changing my global  `'tabLength': 4`, lead to the default value of all the latex grammars in the UI to be updated to 4 as well. There are however no new entries added to `config.cson` in this case.  On changing `'tabLength': 6`, the corresponding entries are added to `config.cson` immediately.  Isn't that the desired behaviour?

**Comment by newton108** [comment]
> > Basically this says if tab length for ".latex.tex.text" is not set, then it disrespects the customised editor tab length, which is fine, but it is not possible to set via UI.
> 
> From a quick skim of [Atoms's docs](https://blog.atom.io/2014/10/31/language-scoped-config.html), this should work by setting up your your global value:
> 
> ```coffee
> 'global': # all languages unless overridden
>   'editor':
>     'tabLength': 4
> ```
> 
> I just tried this on Atom 1.40.1 on Win10, and changing my global `'tabLength': 4`, lead to the default value of all the latex grammars in the UI to be updated to 4 as well. There are however no new entries added to `config.cson` in this case. 

Right after this, it seems that latex grammars in the UI was updated to 4, but if you actually open an .tex file and try tab, it was 2.

**Comment by ashthespy** [comment]
This seems again like a core Atom issue, better to open up an issue upstream.

**Comment by newton108** [comment]
> This seems again like a core Atom issue, better to open up an issue upstream.

What about remove the default setting of tablength of the package, then the default would just be the default of the editor, right? Do you think this is desirable?

**Comment by ashthespy** [comment]
Could you check if removing `tabLength` from [`language-latex.cson`](https://github.com/ashthespy/Atom-LaTeX/blob/8d893e808f65a6ac25f8ae7e3ce9561b71ac28d8/settings/language-latex.cson#L4) solves your issue?

**Comment by newton108** [comment]
> Could you check if removing `tabLength` from [`language-latex.cson`](https://github.com/ashthespy/Atom-LaTeX/blob/8d893e808f65a6ac25f8ae7e3ce9561b71ac28d8/settings/language-latex.cson#L4) solves your issue?

Yes it does:
I have global setting 
```
'global': # all languages unless overridden
  'editor':
    'tabLength': 4
```
The issue was, with `tabLength=2` present in `language-latex.cson`, it overwrites the behaviour of tab length to be 2, but in the UI it thoughts the default is still 4 as global setting, and does not allow it to be changed to 4 (actually it does, for a very short time, then change back as long as the cursor left the field). Hence user cannot customise `tablength` via UI.

Now as `tabLength=2` removed from `language-latex.cson`, it is not needed to change `tablength` for the language latex to the global setting.

**Comment by ashthespy** [comment]
Hmm, I wonder if these defaults added in 47558f9adc7fbfcab30c3434bc57349d37a32672 are still required..

**Comment by newton108** [comment]
> Hmm, I wonder if these defaults added in [47558f9](https://github.com/ashthespy/Atom-LaTeX/commit/47558f9adc7fbfcab30c3434bc57349d37a32672) are still required..

Good question. But I'm not against package-specific default, but the problem is that it overwrites the global customisation by user and not explicit about it.

**Comment by ashthespy** [comment]
Probably also related https://github.com/ashthespy/Atom-LaTeX/issues/20#issuecomment288677305

Guess we can test removing these defaults defined here, as they will always override defaults set in the UI configuration menu.
