### ISSUE TITLE
Check environment variable bibinputs for .bib-files

### ISSUE THREAD

**Issue by kunizial** [ashthespy/Atom-LaTeX#230]
I have a global .bib-file which i sync between PCs running Windows and Linux via cloud. In order to make the .tex-file work on both filesystems and as general as possible, I use the environment variable BIBINPUTS.
Would it be possible to check BIBINPUTS when looking for bibliography-files?

**Comment by ashthespy** [comment]
You could use the [custom toolchain options](https://github.com/ashthespy/Atom-LaTeX#-setting-up-a-toolchain) to export the variable first. Something along the lines of
`export BIBINPUTS=/path/to/directory && %BIB %DOC`

**Comment by ashthespy** [comment]
Closing for now, let me know if you the above options doesn't work for you.

**Comment by kunizial** [comment]
Sorry if i was unclear. The execution of latex out of atom works fine. I was meaning the auto-completion of bibitems doesn't look for the BIBINPUTS variable.
