### ISSUE TITLE
pdf viewer displaying Bad Request

### ISSUE THREAD

**Issue by jchristopherfeng** [ashthespy/Atom-LaTeX#237]
I have atom-latex 0.91, with atom 1.44.0 on Manjaro 19.0.1 Kyria. The pdf viewer no longer displays pdf files---displaying instead the message "Bad Request." This happens even when I disable the other community packages I have installed (language-fortran 21.10, language-latex 1.2.0) The pdfs still compile correctly, but I can't get them to display in the pdf window or tab.

**Comment by eriguezp** [comment]
Same problem here, atom-latex 0.91, atom 1.44.0 on Archlinux

**Comment by ashthespy** [comment]
Could you check if there are compatibility issues again with Arch's version of electron viz what Atom needs? ==> https://github.com/ashthespy/Atom-LaTeX/issues/204#issuecomment-508809012

**Comment by jchristopherfeng** [comment]
I'm running electron 4.2.12. Not sure which versions of electron have compatibility issues with atom.

**Comment by ashthespy** [comment]
That could be the issue - Atom `1.44.0` uses `electron: "4.2.7"`.
>What does it look like for you? If that is indeed the issue, could you try if [`atom-editor-bin`](https://aur.archlinux.org/packages/atom-editor-bin/) also gives you the same hanging behaviour?

**Comment by Bendodroid** [comment]
> Same problem here, atom-latex 0.91, atom 1.44.0 on Archlinux

+1

**Comment by ashthespy** [comment]
@Bendodroid 
> What does it look like for you? If that is indeed the issue, could you try if [`atom-editor-bin`](https://aur.archlinux.org/packages/atom-editor-bin/) also gives you the same hanging behaviour?

**Comment by jchristopherfeng** [comment]
Changing to [`atom-editor-bin`](https://aur.archlinux.org/packages/atom-editor-bin/) resolves the issue for me.

**Comment by eriguezp** [comment]
Changing to atom-editor-bin resolves the issue for me too.

**Comment by ashthespy** [comment]
I'd request one you guys to raise an issue upstream about this - this seems to happen often with Atom on Arch..
