### ISSUE TITLE
Uncaught TypeError: this.trimLatexmk is not a function

### ISSUE THREAD

**Issue by bonStats** [ashthespy/Atom-LaTeX#238]
Getting this error when I build a PDF. I was first seeing [Issue 78](https://github.com/ashthespy/Atom-LaTeX/issues/78) but am now seeing this.

Steps: 

1. Build Latex

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 16.04.6
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.9.1

### Stack Trace

Uncaught TypeError: this.trimLatexmk is not a function

```
At /home/joshua/.atom/packages/atom-latex/lib/parser.coffee:27

TypeError: this.trimLatexmk is not a function
    at Parser.module.exports.Parser.parse (/packages/atom-latex/lib/parser.coffee:27:14)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:112:19)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:45:8)
    at /packages/atom-latex/lib/builder.coffee:77:10)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -0:05.0 intentions:highlight (input.hidden-input)
     -0:04.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.9.1 
atom-updater-linux 1.3.0 
busy-signal 2.0.1 
compare-files 0.8.1 
intentions 1.1.5 
language-matlab 0.2.1 
linter 2.3.1 
linter-spell 0.15.0 
linter-ui-default 1.8.1 
thesaurus 0.3.0 
```

**Comment by ashthespy** [comment]
Greetings again @bonStats. I think there is something fishy going on with your installation/edits.
Could you try reinstalling to ensure this isn't an artefact of our old debugging adventures?

**Comment by bonStats** [comment]
I've installed atom from scratch by:
1. Uninstalled atom, 
2. Deleted the `.atom` folder
3. Reinstalled the latest version following [these instructions](https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux)

Now all seems to be working. I think it might have been my debugging attempts and/or old latex package clashes.
