### ISSUE TITLE
pdf preview tab difficult to resize (shrink) as normal to fast mouse movement stops resizing

### ISSUE THREAD

**Issue by derMart** [ashthespy/Atom-LaTeX#243]
Hi,

using atom-latex 0.9.1 with atom 1.45.0 x64 on Ubuntu 18.04. Having the pdf preview configured as tab and it is on the right side of the atom window. Enlarging the preview tab is no problem, even with normal to fast mouse movement.
Shrinking it however is just possible when moving the mouse very slowly. As soon as the mouse moves too fast (while left click is active) and the mouse moves into the pdf preview window for too long (before the tab reacts to resizing) the resize stops. Quite annoying ... ;-)
Possibly mouseouts from anything left of the pdf preview tab stop resizing?

best
Martin

**Comment by Aerijo** [comment]
This has been fixed in Atom [nightly](https://atom.io/nightly), it will eventually reach beta and then stable.

**Comment by derMart** [comment]
Thanks alot!

**Comment by ashthespy** [comment]
https://github.com/atom/atom/pull/19862 For reference :-)
