### ISSUE TITLE
pdf preview tab is empty in atom-nightly

### ISSUE THREAD

**Issue by derMart** [ashthespy/Atom-LaTeX#244]
Hi,

using atom-latex 0.9.1 together with atom 1.47.0-nightly7 x64 Ubuntu 18.04

When pdf preview is configured as tab the preview tab is just empty with a grey background.
Preview as extra window works though.

best
Martin

**Comment by ashthespy** [comment]
Could you check if there are any errors on the dev console? (`ctrl` + `shift` +`i`). I reckon that nightly is on a different version of chrome, and the `webview/iframe` is again acting up.

**Comment by derMart** [comment]
just checked, nope nearly no output on the console.
Only:
`[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.co/features/4642138092470272 for more details.`

`Uncaught (in promise) Error: NSFW was unable to start watching that directory.`
at start of atom and another Uncaught watch error during or after tex compilation.

But I guess that is not related to this...(?)

**Comment by ashthespy** [comment]
I briefly looked into this - Atom nightly now uses electron 5.x, [disables `webview`](https://github.com/electron/electron/releases/tag/v5.0.0) that we use by default. 
This would mean we would go back to using an `iframe` for the interim. Try the following patch.. 
```diff
diff --git a/lib/viewer.coffee b/lib/viewer.coffee
index 7cdc861..c301194 100644
--- a/lib/viewer.coffee
+++ b/lib/viewer.coffee
@@ -130,7 +130,10 @@ class Viewer extends Disposable
 
 class PDFView
   constructor: (url,title) ->
-    @element = document.createElement 'webview'
+    @element = document.createElement 'iframe'
+    @element.setAttribute 'width', '100%'
+    @element.setAttribute 'height', '100%'
+    @element.setAttribute 'frameborder', 0,
     @element.setAttribute 'src', url
     @element.addEventListener 'console-message', (e) -> console.log e.message
     @title = title
```

**Comment by derMart** [comment]
yep, works like a charm :-)
Now, I am also getting this output on the console which I guess is as expected:
`PDF 04207f4f4a499fc99905289afbd6de30 [1.5 pdfTeX-1.40.18 / LaTeX with hyperref package] (PDF.js: 2.2.228 [WebGL])`

**Comment by derMart** [comment]
not sure if this is related, but another thing is coming up while resizing the preview tab now:
```
text_layer.js:520 Uncaught (in promise) Error: TextLayer task cancelled.
    at TextLayerRenderTask.TextLayer_cancel [as cancel] (text_layer.js:520)
    at TextLayerBuilder.cancel (viewer.js:12387)
    at PDFPageView.cancelRendering (viewer.js:11856)
    at PDFPageView.reset (viewer.js:11737)
    at PDFPageView.update (viewer.js:11841)
    at PDFViewer._setScaleUpdatePages (viewer.js:10716)
    at PDFViewer._setScale (viewer.js:10804)
    at PDFViewer.set (viewer.js:11320)
    at webViewerResize (viewer.js:2057)
    at viewer.js:4034
```
