### ISSUE TITLE
Spell-check exclude commands

### ISSUE THREAD

**Issue by mmarras** [ashthespy/Atom-LaTeX#247]
I'm not sure this is a bug, but is it desired that enabling spell-checking also checks and highlights commands like `\documentclass` etc.? It would be nice if it would not do that. 

OS: Win 10 Enterprise; 10.0.17763 
atom: 1.45.0 x64 
electron: 4.2.7
chrome: 69.0.3497.128
node: v10.11.0
spell-check: 0.75.0
atom-latex: 0.9.1

**Comment by ashthespy** [comment]
This is quite painful given the current structure of Atom's spell check. You would need to manually add all the grammar scopes you want spell check to ignore - and I would consider it out of the scope of this package..
