### ISSUE TITLE
Empty PDF preview in tab

### ISSUE THREAD

**Issue by mshorachi** [ashthespy/Atom-LaTeX#248]
Hi there! I started using you package a few months ago and everything worked perfectly. However, a few days ago the PDF preview that I usually have in an atom tab on the right stopped previewing my PDF and just stayed empty after compiling the code. I'm not getting any errors. If I preview my PDF NOT in another tab (so it will preview in another window that pops up) then it does work and previews my PDF properly. So only the preview PDF in tab function stopped working for me randomly. 

My installed (non-core) packages:
```
- atom beautify 0.33.4
- atom-latex 0.9.1
- file-icons 2.1.41
- highlight-selected 0.17.0
- language-latex 1.2.0
- latex-autocomplete 1.1.1
- pdf-view 0.72.0
- pigments 0.40.2
```
Atom version =1.47.0 (newest)

steps to reproduce: Open my folder, compile the root file and select preview in tab.

**Comment by ashthespy** [comment]
Unfortunately, there have been some upstream changes (https://github.com/atom/atom/issues/20604) that break this package 
See #244 for a possible fix until the upstream Atom version is bumped.

**Comment by mshorachi** [comment]
> Unfortunately, there have been some upstream changes ([atom/atom#20604](https://github.com/atom/atom/issues/20604)) that break things.
> Please downgrade to [Atom v1.46](https://github.com/atom/atom/releases/tag/v1.46.0) skipping the 1.47 update.
> Or, see #244 for a possible fix until the upstream Atom version is bumped.

Downgrading to 1.46.0 indeed solved the issue for me! Thank you for the quick reply!

**Comment by ashthespy** [comment]
Fixed finally by https://github.com/atom/atom/pull/20855  and landing in [Atom v1.48.0](https://github.com/atom/atom/releases/tag/v1.48.0)
