### ISSUE TITLE
Pdf preview not generating

### ISSUE THREAD

**Issue by AaronPenders** [ashthespy/Atom-LaTeX#249]
Dear all

I am experiencing an issue in which I cannot generate a preview pdf of my LaTeX document (see screenshot - forgive my blurring of specific content). There are no build errors with the related document. Going through "Packages" > "Atom-LaTeX" > "Preview PDF" I can generate an up to date pdf version but not in the active window (that option does not work for me). Building LaTeX from the active editor for some reason warns me about setting the active [LaTeX main file](https://github.com/ashthespy/Atom-LaTeX#setting-the-latex-root-file), however this seems to be set according to the home icon link.

![image](https://user-images.githubusercontent.com/42219910/82826903-40fc5c00-9eae-11ea-9dc5-4b081b5a7783.png)

It looks like I'm missing something fairly simple, since it worked before.
Thanks in advance.

**Comment by ashthespy** [comment]
Please see the pinned issue #248

**Comment by AaronPenders** [comment]
Apparently I'm not the only one experiencing this issue, see #244 and #248. Good to know there isn't something wrong on my end. I'll wait until the future upstream Atom version is bumped as explained there. A preview can still be generated through what I explained above.
