### ISSUE TITLE
PDF is not automatically recompiling from .tex file

### ISSUE THREAD

**Issue by BrittanyH1997** [ashthespy/Atom-LaTeX#252]
Hello.

I am writing a simple LaTeX document in Atom. My .tex file runs just fine, but whenever I press ctrl + alt + B, my PDF does not open in a separate project in another pane so I can see them side to side. Every now and then, when I close the PDF and open it again, it takes two tries of pressing ctrl + alt + B for the PDF to recompile with the changes, but now it will not recompile nor has it automatically loaded to the next pane since I started. I have latex, latex-tools, pdf-view, and all other necessary packages installed and nothing reconfigured in the settings of each one and I don't know what to do.

Any help would be greatly appreciated, thanks.

**Comment by ashthespy** [comment]
I would try disabling multiple LaTeX packages to rule out interference issues..

PS: This package is atom-latex ;-)

**Comment by ashthespy** [comment]
Closing this, feel free to chime in to reopen it..
