### ISSUE TITLE
Custom PDF previewer.

### ISSUE THREAD

**Issue by celdorwow** [ashthespy/Atom-LaTeX#256]
Hi,

Can I use a different pdf previewer such as Okular? I can't seem to find anything in settings to let the package know I would use a custom application to see PDFs.

Thanks

**Comment by ashthespy** [comment]
The package doesn't provide a way to use an external viewer as a design choice. It bakes all functionality into one package.

That being said, the pdf preview is being served via a webserver, so you can always open that link in your client.
