### ISSUE TITLE
freezes when typing a backslash

### ISSUE THREAD

**Issue by s4turn** [ashthespy/Atom-LaTeX#257]
Project is large, particularly bibtex. I wonder if the autocomplete is not indexing properly?

**Comment by ashthespy** [comment]
Does anything show up on the dev console? The `/` does indeed trigger autocomplete, but IIRC the bibtex stuff triggers only once you get to the actual `/cite{` command.

**Comment by ashthespy** [comment]
Closing this, feel free to chime in to reopen it..
