### ISSUE TITLE
Error Occurred While Building LaTeX - latexmk not working

### ISSUE THREAD

**Issue by TheOfficialDarthVader** [ashthespy/Atom-LaTeX#258]
**What I've done:**

- Installed `atom-latex`
- Installed ActiveState Perl
- Installed `latexmk` using the MikTex Console
- Set the Windows System Environment variables for Perl and MikTex:
    - For Perl: `C:\Perl64\bin`
    - For MikTex: `C:\Program Files\MiKTeX 2.9\miktex\bin` and `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\`

I can confirm that Perl works as I am able to run both it and the `latexmk` script from Command Prompt. I can also use `latexmk` from TexStudio, but this required setting `Commands ($PATH)` to `C:\Perl64\bin`. I can run `pdflatex` as the build engine in `atom-latex`. It is just `latexmk` that is not working.

Given what I had to do to get Perl scripts to work with TexStudio this would seem to suggest the Environment Variables being passed are in some way incorrect.

The build log is just a single line:
`> latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf  "Cover Letter"`

So I'm not sure where it is getting hung up, I assume it is an issue with not finding Perl.

**Comment by ashthespy** [comment]
As a quick sanity check, try setting your toolchain to just `latexmk --version` to ensure it's not something with your PDF?

**Comment by TheOfficialDarthVader** [comment]
That command fails to run

**Comment by ashthespy** [comment]
You seem to have some other issues here, I would create a debugging `.bat` or `.cmd` file to print out paths (`where latexmk`) and  env variables among other things to confirm everything is correct. 
If Perl is not found, normally you get something along the lines of `latexmk.exe: The script engine could not be found.`  IIRC...

Unfortunately, this is not really something the package can solve.

**Comment by TheOfficialDarthVader** [comment]
Rather frustratingly a restart seems to have fixed the problem. I find this a bit unusual as changes to environment variables are applied immediately. And restarting any program looking for said variable in theory should fix the problem. Guess this comes down to an idiosyncrasy in windows somewhere...
