### ISSUE TITLE
Selecting a new Latex root file causes Atom to crash

### ISSUE THREAD

**Issue by mmarras** [ashthespy/Atom-LaTeX#259]
atom-latex 0.91
atom 1.51.0

When select a new latex root file atom shows file dialog, after file selection and confirmation, atom quits without error.

**Comment by ashthespy** [comment]
I really can't help you debug this as it would be extremely system specific. 
But to give you some avenues to explore:

-- Does it happen on any file?
-- Are they any other packages that might be conflicting? 
--

**Comment by ashthespy** [comment]
Closing this, feel free to chime in to reopen it..
