### ISSUE TITLE
Problem with SyncTeX

### ISSUE THREAD

**Issue by ChrisKonidas** [ashthespy/Atom-LaTeX#261]
Hello. 

I've recently formatted my pc. Before that syncTeX was working fine. I have texlive. 
Every time I try to use ctrl+click I get this error:

Command failed: synctex edit -o "1:237.75078534031417:257.5413612565446:C:\Users\Chris\Desktop\Σχολή\Αλγόριθμοι\Κεφάλαιο 1\K1.pdf"
SyncTeX ERROR: No SyncTeX available for C:\Users\Chris\Desktop\S????\???????�??\?ef??a?? 1\K1.pdf

Thank you.

**Comment by ashthespy** [comment]
This means `No SyncTeX ` was found for your file.. Are you passing the right flags when you compile your tex?
