### ISSUE TITLE
Arara support?

### ISSUE THREAD

**Issue by onekk** [ashthespy/Atom-LaTeX#265]
Any news about arara support?

I have used this package and the only difficult was the build phase.

The argumentation about the implementation difficult is somewhat false.

if you set arara the only command to issue is "arara -v Filename", all the multiple passes and other things are done by arara, the only suport is the pdf visualization with synctex support.

Regards

Carlo D.

**Comment by ashthespy** [comment]
`arara` (or any toolchain for that matter) is supported out of the box.. `arara` is something in particular that I've been using it from way back in 2016..

**Comment by onekk** [comment]
Sorry for the mistake, maybe I've read an old post, or probably ever mistaken the atom extension, as I'm trying some of them.

Best Regards
Carlo D.
