### ISSUE TITLE
Autocomplete on atom+windows

### ISSUE THREAD

**Issue by mmarras** [ashthespy/Atom-LaTeX#269]
Hi, I am struggling to get autocomplete to work on windows (this doesn't imply that I have another non-win system on which it works). 

Failure: Does not autocomplete
Expected Behavior: typing `\begin{document}` should trigger to issue `\end{document}`. 
Reproduce: Make latex document type `\begin{document}`

win10, 
Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

Anything that I need to set-up before it it works, or should be out of the box?

**Comment by mmarras** [comment]
```
C:\Users\#####\AppData\Local\atom\app-1.52.0\resources\app.asar\src\text-editor-element.js:357 [Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
(anonymous) @ C:\Users\######\AppData\Local\atom\app-1.52.0\resources\app.asar\src\text-editor-element.js:357
<embedded>:11 No deserializer found for http://127.0.0.1:58072/viewer.html?file=preview.pdf
deserialize @ <embedded>:11
2C:\Users\######\.atom\packages\turtle-completer\lib\turtle-provider.coffee:19 Config change false for 
2<embedded>:14 TrustedTypes policy dompurify could not be created.
_createTrustedTypesPolicy @ <embedded>:14
manager.coffee:213 RootWatcher Init: 48.807861328125ms
```
Not to me, but no clue.

**Comment by ashthespy** [comment]
-- Do you have any conflicting Latex packages?
-- Can you share a quick screen cap of what is happening? 
For reference, it should look something [like this](https://github.com/ashthespy/Atom-LaTeX/blob/master/figures/command-autocomplete.gif)

**Comment by mmarras** [comment]
No other latex package in atom installed. 

It is doing something at least when you manually close an itemize environment is throws in an `\item`. But please see [a screen capture of the situation](https://github.com/mmarras/mytest/blob/master/latex-autocomplete.gif) as requested.

**Comment by ashthespy** [comment]
You need to hit tab for autocomplete.. So `\begin` <kbd>tab</kbd> and then select what environment is required..

**Comment by mmarras** [comment]
Thanks! Closing and opening works now! 

But to be honest, I would have hoped it to be more robust: opening `{` breaks it. using the cursor with the keyboard-arrow in-between also breaks it, I move two cursors around then 😨. So really one needs to press tabs for right time and once in that mode, don't do something stupid. Btw. `begin{document}` is not in the list of autocompletions?

**Comment by ashthespy** [comment]
This isn't some thing the package can control directly, it's the the normal autocomplete API of most text editors.. Here we use the default [Atom API](https://github.com/atom/autocomplete-plus).
