### ISSUE TITLE
Ignore bibtex if it was not used

### ISSUE THREAD

**Issue by mfbehrens99** [ashthespy/Atom-LaTeX#272]
```
> bibtex main

This is BibTeX, Version 0.99d (MiKTeX 21.3)
The top-level auxiliary file: main.aux
I found no \citation commands---while reading file main.aux
I found no \bibdata command---while reading file main.aux
I found no \bibstyle command---while reading file main.aux
(There were 3 error messages)
```
When I run my LaTeX file I get this error message from BibTeX and the compilation stops with an error. Can we just ignore when no bibtex has been used in the tex file and continue the building process?

**Comment by ashthespy** [comment]
How are you [Setting your toolchain](https://github.com/ashthespy/Atom-LaTeX#-setting-up-a-toolchain)? 
I would advice you to use one of the automatic LaTeX helper utilities so you don't need to manually mange this and focus on finishing your paper ;-)
