### ISSUE TITLE
How to use lualatex to compile CV

### ISSUE THREAD

**Issue by ChengzhiYin** [ashthespy/Atom-LaTeX#274]
Need to compile my cv using lualatex. Do you know how to set lualatex as my compiler? Thanks.

**Comment by ashthespy** [comment]
Did you have a look at the Readme? Particularly the section on [setting up a toolchain?](https://github.com/ashthespy/Atom-LaTeX#-setting-up-a-toolchain)

**Comment by ChengzhiYin** [comment]
Thanks. I have solved the problem.
