### ISSUE TITLE
Keymapping Save, Build, then Preview

### ISSUE THREAD

**Issue by ReturnInfinite** [ashthespy/Atom-LaTeX#275]
Apologies if this is easy to answer, I've looked into it and I don't know how I'm meant to go about this.
I use atom-latex and pdf-view, and would like to be able to check my work as I go along, but I keep having to close the PDF tab > rebuild > preview the file manually.
Is there a way to maybe keymap (I was thinking alt-f1) to close the current preview tab, save the .tex file, then build and preview with atom-latex?
(would also accept any help if I'm totally missing features)

**Comment by ashthespy** [comment]
The inbuilt viewer auto updates on a fresh build - is there a reason you don't use that?

**Comment by ReturnInfinite** [comment]
Mine doesn't, I'm not sure why. I have to close the current PDF window and then ctrl-l, ctrl-t to get a preview of the new build

**Comment by ashthespy** [comment]
Could you open up the dev console and share what is on there? Something seems amiss..

**Comment by ashthespy** [comment]
Feel free to post back info when you have some updates!
