### ISSUE TITLE
I cannot build a Pweave project

### ISSUE THREAD

**Issue by starlinq** [ashthespy/Atom-LaTeX#278]
It was reported that Sweave build is supported by custom toolchain command, e.g. [here](https://github.com/ashthespy/Atom-LaTeX/issues/42). 

In local directory I created .latexcfg file:
`{
"root": "test.Pnw",
"toolchain": "\"C:\Users\myusername\anaconda3\Scripts\activate.bat\" pweave && C:\Users\myusername\anaconda3\envs\pweave\Scripts\pweave -f tex %DOC.Pnw && %TEX %ARG %DOC.tex && %TEX %ARG %DOC.tex && \"C:\Users\myusername\anaconda3\condabin\conda.bat\" deactivate",
"latex_ext": [".Pnw", ".pnw", ".texw", ".tex"]
}` 

Now I am trying to do the same with (LaTeX + Python with noweb syntax) Pweave (.Pnw) project under Windows and I cannot do it. Atom-LaTeX panel is not available as well.

I believe that a fix for this issue is not so difficult. Can you help?

**Comment by ashthespy** [comment]
The plugin lazy loads only when it detects an editor with a recognised TeXish grammar. As your `.pnw` file isn't auto detected as TeX, it doesn't load. You can manually set the grammar to TeX by hitting `crt`+`shift`+`l` and select `LaTeX` or `Tex`.

Let me know if that works..

**Comment by starlinq** [comment]
> The plugin lazy loads only when it detects an editor with a recognised TeXish grammar. As your `.pnw` file isn't auto detected as TeX, it doesn't load. You can manually set the grammar to TeX by hitting `crt`+`shift`+`l` and select `LaTeX` or `Tex`.
> 
> Let me know if that works..

@ashthespy Thank you for your quick response. Yes, it works as you said. I had to change the grammar to 'LaTeX' (text.tex.latex). Originally I used the grammar as 'Pweave Latex' (source.pweave.latex) which in theory must be a better match the file type. My loss after using this workaround is a 'Pweave' syntax highlighting. Can we add the 'Pweave Latex' (source.pweave.latex) grammar to recognizable grammar group for the extension?

**Comment by starlinq** [comment]
Unfortunately, after some testing a more serious issue has appeared. I changed the grammar only without changing the original file extension '.pnw' (it is basically a 'LaTeX' file with Python code chunks of the noweb syntax). When start compiling, it randomly picks another file (not currently opened in the editor) with '.tex' extension in the same directory! I have several versions of the document, the versions have a common base name and the they have different '_vXX' endings.

**Comment by ashthespy** [comment]
>The Atom-LaTeX panel is visible now, however running build does not work, it asks me to specify a root file (actually I did it, but it does not recognize my settings probably because of the '.pnw' file extension).


You would need to have your `.pnw` in your project, and the `.latexcfg` as well. So something like this. 

```
{
    "root": "test.pnw",
    "toolchain": "arara %DOC -v",
    "latex_ext": [
        ".tex",
        ".pnw"
    ]
}
```

> Originally I used the grammar as 'Pweave Latex' (source.pweave.latex) which in theory must be a better match the file type. In addition, my loss after trying this workaround is a 'Pweave' syntax highlighting. Can we add the 'Pweave Latex' (source.pweave.latex) grammar to recognizable grammar group for the extension?

This package activates on detection of `text.tex.latex`, which should be a included as a scope in `source.pweave.latex`? But I am not sure how that particular grammar works. 
You could always edit your copy of the package to activate explicitly for this grammar. 
https://github.com/ashthespy/Atom-LaTeX/blob/991e6721ac65e4b11e815e4cb53ea554f6b5c63b/lib/main.coffee#L12-L17

**Comment by starlinq** [comment]
@ashthespy Thank you for your response. Yes, I will try your suggestion.

Here is mwe.pnw file content:

`
\documentclass{article}
\begin{document}

Invisible code that sets the value of the variable $a$.

<<echo=False>>=
a = 3.14
@

Visible code that sets $b$ and squares it.

<<term=True>>=
b = 3.15
print(b*b)
@

The assigned value is <%= b %>.

\end{document}
`

**Comment by ashthespy** [comment]
The plugin seems to be doing what is expected - I have this as my `.latexcfg` and your snippet as `test.pnw`.
```
{
    "root": "test.pnw",
    "toolchain": "pweave -f tex %DOC.%EXT",
    "latex_ext": [
        ".tex",
        ".pnw"
    ]
}
```

It shells out to and runs the command fine - but in my case it errors out.

I did spend a few minutes installing `pweave`, but gave up cause I couldn't get it to compile directly from the command line either. , something about
```
> pweave -f texpweave test.pnw
<snip>
  File "...\lib\site-packages\pweave\readers.py", line 132, in getoptions
    exec("chunkoptions =  dict(" + optstring + ")", opt_scope)
  File "<string>", line 1, in <module>
NameError: name 'FALSE' is not defined
```

So I would first check if the custom toolchain commands are being launched by the package, and if so then debug the command itself.

**Comment by starlinq** [comment]
Here is my Windows batch script for compiling .pnw files. It works well from command line but I failed to get any success if I put its call in .latexcfg config file.

```
@echo off

echo "Compile script for pweave noweb documents (.pnw) under Windows OS"
echo "Requires a LaTeX installation"
echo "Requires a Python installation in form of anaconda distribution in user directory"
echo "Requires a creation of Python virtual environment with name 'pweave'"
echo "Requires conda package installation with name 'pweave' (within the environment)"
echo "Usage example, e.g.: build.bat test.pnw"

set filename=%1
set filenamenoext=%~n1
REM To adjust to your system setup, in the path string below, replace 'yourusername' with your own 
set pathtoanaconda="C:\Users\yourusername"

echo "Compiling ...%filename%"

echo "activativating conda pweave environment and compiling by pweave ..."

CALL "%pathtoanaconda:"=%\anaconda3\Scripts\activate.bat" pweave 

"%pathtoanaconda:"=%\anaconda3\envs\pweave\Scripts\pweave.exe" -f tex %filename%

echo "compiling %filenamenoext%.tex by pdflatex ... into %filenamenoext%.pdf"

pdflatex -synctex=1 -interaction=nonstopmode %filenamenoext%.tex
pdflatex -synctex=1 -interaction=nonstopmode %filenamenoext%.tex

CALL "%pathtoanaconda:"=%\anaconda3\condabin\conda.bat" deactivate

echo "Complete"
```

**Comment by ashthespy** [comment]
What happens when you set your  `toolchain` to `build.bat`?  i.e `"toolchain": "build.bat %DOC.%EXT"`

**Comment by starlinq** [comment]
@ashthespy 
Finally I have managed to get a positive result, in my local installation, I just added one line to the `main.coffee` file:

```
@disposables.add atom.workspace.observeTextEditors (editor) =>
      return if @activated
      editor.observeGrammar (grammar) =>
        if (grammar.packageName is 'atom-latex') or
           ((grammar.scopeName.indexOf('text.tex.latex') > -1) or
            (grammar.scopeName.indexOf('source.pweave.latex') > -1)) or
           (grammar.name is 'LaTeX')
          promise = new Promise (resolve, reject) =>
            setTimeout(( => @lazyLoad()), 100)
            resolve()
```

Also according to your suggestion, I set the toolchain command so .latexcfg file is as:

```
{
"root": "test.pnw",
"toolchain": "build.bat %DOC.%EXT",
"latex_ext": [".Pnw", ".pnw", ".texw", ".tex"]
}
```

**Comment by ashthespy** [comment]
Great! If you want to dig deeper, you could always check why the grammar isn't exposing the `text.tex` scope.
Will call this success for now, enjoy writing!

**Comment by starlinq** [comment]
@ashthespy Thank you for your time! I will enjoy writing such files, definitely. 

I am having a small issue relating to 'Pweave Latex' syntax highlighting (it comes from [package](https://github.com/JunoLab/language-weave)). I already reported the issue [here](https://github.com/JunoLab/language-weave/issues/47) but it seems their package if not abandoned, is not on high priority list for support (currently I got no responses).

**Comment by ashthespy** [comment]
Well, the grammar isn't the most comprehensive..
But you can get by adding something along these lines: 
 `\.atom\packages\atom-latex\grammars\pweave.cson`
```cson
fileTypes: [
  'ptexw'
  'pnw'
]
name: 'Pweave LaTex'
scopeName: 'source.pweave.latex'
patterns: [
    {
      include : 'text.tex.latex'
    }
    {
      begin: '(^<<)(.*?)(>>=)\\s*$'
      beginCaptures:
        1:
          name: 'markup.heading.pweave.noweb'
        2:
          contentName: 'source.embedded.python'
          patterns: [
            {
              include: 'source.python'
            }
          ]
        3:
          name : 'markup.heading.pweave.noweb'
      end: '^(@)\\s*$'
      endCaptures:
        1:
            name: 'markup.heading.pweave.noweb'
      contentName: 'source.embedded.python'
      patterns: [
        {
          include: 'source.python'
        }
      ]
    }
    {
      begin: "<%=?"
      beginCaptures:
        "0":
          name: "punctuation.definition.string.begin.pweave"
      end: "%>"
      endCaptures:
        "0":
          name: "punctuation.definition.string.end.pweave"
      name: "string.other.pweave.python"
      patterns: [
        {
          include: 'source.python'
        }
      ]
    }
  ]

```

The inline `$\sqrt{2} = <%= sqrt(2) %>$`  is a bit more involved you might need to explore the other grammars to see how it is done.
