### ISSUE TITLE
No pdf preview when out_dir is defined in latexmkrc

### ISSUE THREAD

**Issue by WSDeWitt** [ashthespy/Atom-LaTeX#279]
First off, thank you for this wonderful package!

My project has a `latexmkrc` containing:
```
$out_dir = 'build';
```
and atom-latex correctly builds in this directory. However, the pdf preview is not rendered when using the "Build LaTeX" or "Preview PDF" commands.

**Comment by ashthespy** [comment]
Greetings, 
This is on the wish list over at #196 but to be honest, I feel we are a dying breed who still use Atom + I don't have much time these days for this package.

A super hacky solution is https://github.com/ashthespy/Atom-LaTeX/issues/196#issuecomment-825093105 of course.
