### ISSUE TITLE
Is there a way to auto-detect the root based on same file & folder patterns?

### ISSUE THREAD

**Issue by onurcanbektas** [ashthespy/Atom-LaTeX#281]
Is there a way to auto-detect the root based on same file & folder patterns?

For instance, all of my folders are organised in

```
Main/
Main -> main.tex
Main -> chapters/
Main -> chapters/ -> ch1/
Main -> chapters/ -> ch1/ -> ch1.tex
```

So, when I'm focussed on ch1.tex on the editor and press build buttton, I want it to set the root to `Main -> main.tex` and build it.

**Comment by ashthespy** [comment]
Have you seen the Readme's [Project-based Configuration](https://github.com/ashthespy/Atom-LaTeX#-project-based-configuration) section? Does that do what you need?
