### ISSUE TITLE
Unable to compile files when files are in folder in M1

### ISSUE THREAD

**Issue by Alex2134556** [ashthespy/Atom-LaTeX#284]
Hello, I recently got my new laptop and I tried to download MacTex and Atom on it. However, for some reason, it isn't letting me compile anything on it, whereas the texmaker software is able to compile the file.

For example even a simple: \documentclass{article}\begin{document}test\end{document}

gives me:
\> latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf abc

Latexmk: applying rule 'pdflatex'...
Latexmk: Errors, so I did not complete making targets

in the log file (that's it). At times it outputs the following in the log-file but no pdf

\> pdflatex -synctex=1 -interaction=nonstopmode -file-line-error abc.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
restricted \write18 enabled.
entering extended mode
(./abc.tex

I tried updating latexmk and that didn't solve the issue. Does anyone have any thoughts?
Would be really delightful if someone can help me with this!

**Comment by ashthespy** [comment]
Can you run the same commands via the terminal?

**Comment by Alex2134556** [comment]
Thanks for the response. Yes, as I mentioned, everything works perfectly fine elsewhere. Typing pdflatex abc.tex or typing latexmk abc.tex directly in the terminal generates the pdf with no issues.

**Comment by ashthespy** [comment]
Then it's possible that there is something funky going on with the shell that is spawned from within electron. I can't really help debug as I don't have one.. Sorry!

**Comment by Alex2134556** [comment]
Oh okay. So your suggestion is to wait it out for newer updates to Atom? I think that's quite possible because other Atom Latex compilers, like a package called latex, also fails to compile the latex files on my Atom.

**Comment by ashthespy** [comment]
That is just what I feel -- you could always debug more to figure out what is happening ;-)

**Comment by Alex2134556** [comment]
Oh, for some strange reason, I am able to compile a tex file via atom-latex if I save the file via the TeXShop. More specifically: TeXShop> Templates> Latex Template> Save. Then I opened the saved tex file via atom-latex and tried to compile it and that works perfectly. So it couldn't be the atom/electron thing? Otherwise it won't work for any file.

**Comment by ashthespy** [comment]
In the past some people have had sandboxing issues with flatpacks/snap version of Atom. Not sure if that could be what is going on. 
Either way, some common debug hints 
- open up the dev console and see if there is anything suspicious going on there. 
- try spawning a shell form atom and run your pdf build commands there and see if that works.

**Comment by Alex2134556** [comment]
Apologies, I am not tech-literate. Can you provide a more handholded version of the hints you are mentioning?

**Comment by ashthespy** [comment]
1. Dev console --> `Ctrl + Shift + i`
Once there you can try (with your document you want to compile open and selected as root) enter and check if this makes sense.
``
atom_latex.latex.mainFile
```

**Comment by Alex2134556** [comment]
I am a still bit unsure. I was able to start Dev console (View > Developer > Open in Dev Mode > Console). However, I am not sure how to do the "with your document you want to compile open and selected as root". I have my latex file open in one of the tabs, and just typing "atom_latex.latex.mainFile" in the console window returns "undefined".

**Comment by ashthespy** [comment]
Sorry, I am in between multiple things so have to be a bit vague..
1. open the console 
2. try building your document
3. copy any messages you see there over here 
4. try entering `atom_latex.latex.mainFile` to see if the usual suspects are not in play

**Comment by Alex2134556** [comment]
Okay so I interpreted the "try building your document" as me trying to compile the latex file while the console was open. 
So I have the simple file "abc.tex" (the above one) and a bit complex latex file "Homework.tex"
After I compiled abc.tex, I tried compiling a bit advanced homework file and following are the results (the yellow errors were present for both): 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/95665546/145084075-60386f62-59cc-4d79-944c-d8cd7bad6290.png">

**Comment by Alex2134556** [comment]
I simply reinstalled the operating system and this time I didn't transfer the data from my old non-M1 Mac. And now everything works fine.

**Comment by ashthespy** [comment]
Glad you got things running, from your logs what you say makes sense, as you have a bunch of Permission errors (EPERM)  

Hope you have a productive homework session after this little procrastination trip ;-)

**Comment by Alex2134556** [comment]
Ah, that makes sense! Thanks a lot for your urgent attention and for your wonderful creation: atom-latex.
