### ISSUE TITLE
XeLaTeX and PDFLatex

### ISSUE THREAD

**Issue by philipplk** [ashthespy/Atom-LaTeX#288]
Dear all,

I am mostly using pdflatex. However, in one project I need to compile the root file with XeLaTeX.

Thus I included a .latexcfg file into the project with the content:

`{ "toolchain" : "xelatex -pdf %DOC" }
`

Now, if switch between projects, all of them are compiled with xelatex. They don't all have a .latexcfg file.

I thought, atom-Latex would use its default toolchain if no config file is in the project folder.

How can I fix this issue?
Thanks in advance.

Cheers
Philipp

**Comment by ashthespy** [comment]
Could you give a more detailed view of your project structure? 

It looks like when you switch to a new project, it's not able to perform that switch fully, and still is using the old one..

**Comment by philipplk** [comment]
Lets say I have two project folders:

ProjectA which requires XeLatex and has a .latexcfg file
ProjectB which requires PDFLatex and has no.latexcfg file

I compile mainA.tex in Project A with cmd+b and it uses xelatex.
Then I with to ProjectB and use cmd+h to compile mainB.tex and it still uses xelatex.

Using another .latexcfg file works but I use endless numbers of projects and don't want to include a .latexcfg file everywhere, because the large majority uses pdflatex.

**Comment by ashthespy** [comment]
> Then I with to ProjectB and use cmd+h to compile mainB.tex and it still uses xelatex.

But does ProjectB have anyway to figure out the correct [root file](https://github.com/ashthespy/Atom-LaTeX#setting-the-latex-root-file)? I'd guess that when in ProjectB, the root file is still pointing to ProjectA..

**Comment by ashthespy** [comment]
To be honest, Atom's multi project handling in a single workspace isn't the best. 
To top it of, my attempt at figuring our multiple projects is [also particularly naive](https://github.com/ashthespy/Atom-LaTeX/blob/991e6721ac65e4b11e815e4cb53ea554f6b5c63b/lib/manager.coffee#L16-L24).  I just use the first active editor and use that to determine the project root. 

I'd say the least effort way would be to open a new window for each project.. Not very helpful, I know.

**Comment by philipplk** [comment]
Thanks @ashthespy !

I will try to work it out and leave a comment if I will be able to fix it.

**Comment by ashthespy** [comment]
I close this for now, feel free to get back when/if you have updates..
