### ISSUE TITLE
when using \ref{..} or \eqref{..} (or other variants), display an autocomplete list of previously cited labels?

### ISSUE THREAD

**Issue by lpry** [ashthespy/Atom-LaTeX#289]
So, if at some point in my .tex file, I have

```
\begin{equation}
    \int e^{-\frac 12 x^2}  \mathrm{d}x \label{eq:impos}
\end{equation}
```

when I type `\ref{`, the editor suggests `eq:impos` as an autocomplete option?

Would be very useful! Would get around to it myself but I'm very out of touch with js and the Atom package structure

**Comment by ashthespy** [comment]
You mean like in [GALLERY.md#autocomplete](https://github.com/ashthespy/Atom-LaTeX/blob/master/GALLERY.md#autocomplete)?
