### ISSUE TITLE
Calling new build during a build causes build error

### ISSUE THREAD

**Issue by gokhansolak** [ashthespy/Atom-LaTeX#291]
Hello, this may sound obvious that running a new build before the previous build ended causes an error, but I think it would be more user friendly if this didn't happen. I think the technical reason that the error happens is that the auxiliary files of the previous build are still there, and the next build cannot modify them. So, the solution could be either:

- Halting the previous build and cleaning auxiliary files.
- Waiting until the previous build is finished, and then starting the next build.
- Not accepting new build until the previous finished.

System: Ubuntu 18.04, Atom 1.52.0, Atom-latex 0.9.1.

**Comment by ashthespy** [comment]
Hmm, well the current method is rather [brute force](https://github.com/ashthespy/Atom-LaTeX/blob/b8f3c80f71c2a2d44a6be917af93d94a96a8d3aa/lib/builder.coffee#L15) of your first option. The second two options don't make much sense, especially if you for example have "Build on Save" enabled.. 

So currently on any build trigger, it checks if there is a running build, and then kills it. This probably leads to a non-zero exit code, and then you get a failed build toast..

**Comment by gokhansolak** [comment]
If the first one works, then it is a solution, but I think it doesn't work as expected. In the current state, it will create an error and the pdf will not be created, so the document is lost until the next successful build. Because, the second build process fails as it cannot modify the aux files, since the first process uses them.

This could be fixed by "kill + wait until killed + rebuild" instead of "kill + rebuild" maybe?

**Comment by ashthespy** [comment]
> Because, the second build process fails as it cannot modify the aux files, since the first process uses them.

That shouldn't be the case.  When the main build process is spawned, the PID is stored and that is used to kill it, and all child processes that were spawned by the build tool.   

Have you tried opening up the dev console and seeing if you are seeing some errors from https://github.com/ashthespy/Atom-LaTeX/blob/b8f3c80f71c2a2d44a6be917af93d94a96a8d3aa/lib/builder.coffee#L142-L145

You could also switch that call to `execSync` to ensure that the kill command completes..

**Comment by gokhansolak** [comment]
Ok, I just checked the console. That is exactly where things went wrong. Logged at line 143 of `builder.coffee`:
```
Error: Command failed: pkill -P 9463

    at ChildProcess.exithandler (child_process.js:303)
    at ChildProcess.emit (events.js:200)
    at maybeClose (internal/child_process.js:1021)
    at Socket.<anonymous> (internal/child_process.js:430)
    at Socket.emit (events.js:200)
    at Pipe.<anonymous> (net.js:586)
```

`execSync` gives the exact same error.

Then, the second build fails by an error like: "<file>.aux: File ended while scanning use of <command>"

**Comment by ashthespy** [comment]
Right, then its not a timing/race condition, but probably some permissuon issue. 

Is atom running in some type of sandbox environment?

**Comment by ashthespy** [comment]
Ah, glad it works. not sure why the `pkill` command doesn't work for you. 

> There is a minor issue though, the icon in the bottom left shows a green checkmark instead of the revolving gear during the second build.

PRs welcome ;) 
Although I use this to write LaTeX, I think we are the last yet people who hang on to Atom and haven't jumped ship to VSCode..

**Comment by gokhansolak** [comment]
Thank you! I looked at it some today, but couldn't solve it. Parser.parse() updates the status icon depending on some keywords in the log message. The first build process sends a log when it is killed after the second build sets the icon to 'building', so it is reset. Anyway, it is a minor thing.

Thank you for your help! This package is very useful to me!
